// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadWarden returns the embedded CollectionSpec for Warden.
func LoadWarden() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WardenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Warden: %w", err)
	}

	return spec, err
}

// LoadWardenObjects loads Warden and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*WardenObjects
//	*WardenPrograms
//	*WardenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadWardenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadWarden()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// WardenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WardenSpecs struct {
	WardenProgramSpecs
	WardenMapSpecs
	WardenVariableSpecs
}

// WardenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WardenProgramSpecs struct {
	WardenRename *ebpf.ProgramSpec `ebpf:"warden_rename"`
	WardenRmdir  *ebpf.ProgramSpec `ebpf:"warden_rmdir"`
	WardenUnlink *ebpf.ProgramSpec `ebpf:"warden_unlink"`
}

// WardenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WardenMapSpecs struct {
	ConfigMap        *ebpf.MapSpec `ebpf:"config_map"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	UidFilterEnabled *ebpf.MapSpec `ebpf:"uid_filter_enabled"`
	UidFilterMap     *ebpf.MapSpec `ebpf:"uid_filter_map"`
}

// WardenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WardenVariableSpecs struct {
}

// WardenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadWardenObjects or ebpf.CollectionSpec.LoadAndAssign.
type WardenObjects struct {
	WardenPrograms
	WardenMaps
	WardenVariables
}

func (o *WardenObjects) Close() error {
	return _WardenClose(
		&o.WardenPrograms,
		&o.WardenMaps,
	)
}

// WardenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadWardenObjects or ebpf.CollectionSpec.LoadAndAssign.
type WardenMaps struct {
	ConfigMap        *ebpf.Map `ebpf:"config_map"`
	Events           *ebpf.Map `ebpf:"events"`
	UidFilterEnabled *ebpf.Map `ebpf:"uid_filter_enabled"`
	UidFilterMap     *ebpf.Map `ebpf:"uid_filter_map"`
}

func (m *WardenMaps) Close() error {
	return _WardenClose(
		m.ConfigMap,
		m.Events,
		m.UidFilterEnabled,
		m.UidFilterMap,
	)
}

// WardenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadWardenObjects or ebpf.CollectionSpec.LoadAndAssign.
type WardenVariables struct {
}

// WardenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadWardenObjects or ebpf.CollectionSpec.LoadAndAssign.
type WardenPrograms struct {
	WardenRename *ebpf.Program `ebpf:"warden_rename"`
	WardenRmdir  *ebpf.Program `ebpf:"warden_rmdir"`
	WardenUnlink *ebpf.Program `ebpf:"warden_unlink"`
}

func (p *WardenPrograms) Close() error {
	return _WardenClose(
		p.WardenRename,
		p.WardenRmdir,
		p.WardenUnlink,
	)
}

func _WardenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed warden_bpfeb.o
var _WardenBytes []byte
